apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tracker-prod

resources:
  - ../../base
  - namespace.yaml

replicas:
  - name: core-api
    count: 2

configMapGenerator:
  - name: core-api-config
    literals:
      - DB_HOST=host.docker.internal
      - DB_PORT=5432
      - DB_NAME=tracker_prod
      - REDIS_HOST=host.docker.internal
      - REDIS_PORT=6379
      - KAFKA_BOOTSTRAP_SERVERS=host.docker.internal:9092
      - SPRING_PROFILES_ACTIVE=prod

secretGenerator:
  - name: core-api-secret
    envs:
      - .env.secret
  - name: core-api-migrator-secret
    envs:
      - .env.migrator.secret

images:
  - name: tracker
    newTag: prod
